### ISSUE TITLE
`insert-annotations-to-source` inserting annotations from Constructor at the field where it was non-present

### ISSUE THREAD

**Issue by the1derer** [typetools/annotation-tools#216]
`insert-annotation-to-source` is inserting annotation that was present on Constructors to field where is was non-present.
"Step to reproduce" uses `@SideEffectFree` but using `@RequiresNonNull` or `@Deprecated`  instead of `@SideEffectFree` also yields the same result i.e. Annotation at the wrong place. This means this bug is not isolated to just `@SideEffectFree`

### To reproduce:

**Test.java**(Annotated)
```java
import org.checkerframework.dataflow.qual.SideEffectFree;
class Test {

  Object value;

  @SideEffectFree
  public Test(){

  }
}
```
```
export CLASSPATH=checker-qual.jar
javac Test.java
extract-annotations Test.class
```
**Test.jaif**
```
package org.checkerframework.dataflow.qual:
annotation @SideEffectFree: @java.lang.annotation.Retention(value=RUNTIME) @java.lang.annotation.Target(value={METHOD,CONSTRUCTOR})

package :
class Test:

    field value:

    method <init>()V: @org.checkerframework.dataflow.qual.SideEffectFree
        return:

```

**Test.java**(Unannotated)
```java
class Test {

  Object value;

  public Test(){

  }
}
```
```
insert-annotations-to-source -i=true Test.jaif Test.java
```
**Result**
```java
import org.checkerframework.dataflow.qual.SideEffectFree;
class Test {

  Object @SideEffectFree value;

  public Test(){

  }
}
```

**Note**:- This problem is only caused if `@SideEffectFree` is on Constructor. That is if there is `@SideEffectFree` on method there will be no error.

Example: (There will be no error in this case)
```java
import org.checkerframework.dataflow.qual.SideEffectFree;
class Test {

  Object value;

  @SideEffectFree
  public void test(){

  }
}
```

**Comment by mernst** [comment]
Could you please minimize the test case?
That is, please find a smaller .java file and a smaller .jaif file that reproduce the error.
That will assist me (or you!) in debugging the problem.
Thanks!

**Comment by the1derer** [comment]
@mernst 
making the test case revealed a much greater problem. That is you can find extra non-present modifier while using `-i=true` option while using `insert-annotations-to-source`

**Test.java**(Annotated)
```java
import org.checkerframework.dataflow.qual.SideEffectFree;
class Test {

  Object value;

  @SideEffectFree
  public Test(){

  }
}
```
```
export CLASSPATH=checker-qual.jar
javac Test.java
extract-annotations Test.class
```

**Test.jaif**
```
package org.checkerframework.dataflow.qual:
annotation @SideEffectFree: @java.lang.annotation.Retention(value=RUNTIME) @java.lang.annotation.Target(value={METHOD,CONSTRUCTOR})

package :
class Test:

    field value:

    method <init>()V: @org.checkerframework.dataflow.qual.SideEffectFree
        return:

```

**Test.java**(Unannotated)
```java
class Test {

  Object value;

  public Test(){

  }
}
```
```
insert-annotations-to-source -i=true Test.jaif Test.java
```

**Result**
```java
import org.checkerframework.dataflow.qual.SideEffectFree;
class Test {

  private Object @SideEffectFree value;

  public Test(){

  }
}
```

Should I create another issue for this?
If this is true it would mean This is going to be our top-most priority as I have used `-i=true` in my script to transfer-annotations.

**Comment by the1derer** [comment]
> Could you please minimize the test case?
Done

**Comment by mernst** [comment]
This is a very useful minimization!  Thanks.

**Comment by the1derer** [comment]
Thanks for the feedback.
I would like to work on this.

**Comment by mernst** [comment]
I saw your message after I had started to work on the issue (because I didn't want you to get blocked).
I believe it is fixed now.

**Comment by the1derer** [comment]
Thank you very much for fixing the bug.

**Comment by the1derer** [comment]
This is till present in field that are defied 
### To reproduce:

**Test.java**(Annotated)
```java
import org.checkerframework.dataflow.qual.SideEffectFree;
class Test {

  Object value;
  Object value2= new Object();

  @SideEffectFree
  public Test(){

  }
}
```
```
export CLASSPATH=checker-qual.jar
javac Test.java
extract-annotations Test.class
```
**Test.jaif**
```
package org.checkerframework.dataflow.qual:
annotation @SideEffectFree: @java.lang.annotation.Retention(value=RUNTIME) @java.lang.annotation.Target(value={METHOD,CONSTRUCTOR})

package :
class Test:

    field value:

    field value2:

    method <init>()V: @org.checkerframework.dataflow.qual.SideEffectFree
        return:
```

**Test.java**(Unannotated)
```java
class Test {

  Object value;
  Object value2= new Object();

  public Test(){

  }
}
```
```
insert-annotations-to-source -i=true Test.jaif Test.java
```
**Result**
```java
import org.checkerframework.dataflow.qual.SideEffectFree;
class Test {

  Object value;
  Object value2= new @SideEffectFree Object();

  public Test(){

  }
}
```

**Comment by the1derer** [comment]
@mernst  This is still present for the following:
### To reproduce:

**Test.java**(Annotated)
```java
import org.checkerframework.dataflow.qual.SideEffectFree;

public class Test {

 Test t = this;

@SideEffectFree
public Test() {}

}

```
```
export CLASSPATH=checker-qual.jar
javac Test.java
extract-annotations Test.class
```
**Test.jaif**
```
package org.checkerframework.dataflow.qual:
annotation @SideEffectFree: @java.lang.annotation.Retention(value=RUNTIME) @java.lang.annotation.Target(value={METHOD,CONSTRUCTOR})

package :
class Test:

    field t:

    method <init>()V: @org.checkerframework.dataflow.qual.SideEffectFree
        return:
```

**Test.java**(Unannotated)
```java
public class Test {

 Test t = this;

public Test() {}

}
```
```
insert-annotations-to-source -i=true Test.jaif Test.java
```
**Result**
```java
import org.checkerframework.dataflow.qual.SideEffectFree;
public class Test {

 Test t = @SideEffectFree this;

public Test() {}

}
```

**Comment by the1derer** [comment]
@mernst  New full Test-Case
### To reproduce:

**Test.java**(Annotated)
```java
import org.checkerframework.dataflow.qual.SideEffectFree;
public class Test {

  Object[] stackTrace = new Object[0];

  Object value;
  Object value2= new Object();

  Test t = this;

  @SideEffectFree
  public Test() {
  }

}
```
```
export CLASSPATH=checker-qual.jar
javac Test.java
extract-annotations Test.class
```
**Test.jaif**
```
package org.checkerframework.dataflow.qual:
annotation @SideEffectFree: @java.lang.annotation.Retention(value=RUNTIME) @java.lang.annotation.Target(value={METHOD,CONSTRUCTOR})

package :
class Test:

    field stackTrace:

    field value:

    field value2:

    field t:

    method <init>()V: @org.checkerframework.dataflow.qual.SideEffectFree
        return:

```

**Test.java**(Unannotated)
```java
public class Test {

  Object[] stackTrace = new Object [0];

  Object value;
  Object value2= new Object();

  Test t = this;

  public Test() {
  }

}
```
```
insert-annotations-to-source -i=true Test.jaif Test.java
```
**Result**
```java
import org.checkerframework.dataflow.qual.SideEffectFree;
public class Test {

  Object[] stackTrace = new Object @SideEffectFree [0];

  Object value;
  Object value2= new Object();

  Test t = this;

  public Test() {
  }

}
```

**Comment by mernst** [comment]
This last variant is hard to fix.  The others could be worked around, but this exposes the fundamentally bad design of having a set of `Criteria` objects rather than a path.
